# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: RV32I
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: C:\Users\Leo\Desktop\FRISCV\FRISCV-apps\asm\src\adds.a
#
#
<1,0>	00000000  13 05 00 40 ;        addi x10, x0, 0x400
<2,0>	                      ;
<3,0>	00000004  93 00 10 00 ;        addi x1, x0, 0x1
<4,0>	00000008  13 01 20 00 ;        addi x2, x0, 0x2
<5,0>	0000000C  93 01 30 00 ;        addi x3, x0, 0x3
<6,0>	00000010  13 02 40 00 ;        addi x4, x0, 0x4
<7,0>	00000014  93 02 50 00 ;        addi x5, x0, 0x5
<8,0>	                      ;        
<9,0>	00000018  23 20 15 00 ;        sw x1, 0(x10)
<10,0>	0000001C  23 22 25 00 ;        sw x2, 4(x10)
<11,0>	00000020  23 24 35 00 ;        sw x3, 8(x10)
<12,0>	00000024  23 26 45 00 ;        sw x4, 12(x10)
<13,0>	00000028  23 28 55 00 ;        sw x5, 16(x10)
<14,0>	                      ;
<15,0>	0000002C  37 1D 00 00 ;        lui s10, %hi(0xFFC);
<16,0>	00000030  13 0D CD FF ;        addi s10, s10, %lo(0xFFC);
<17,0>	00000034  93 0D 70 01 ;        addi s11, x0, 0x17;
<18,0>	00000038  23 20 BD 01 ;        sw s11, 0(s10)
<19,0>	                      ;
<20,0>	                      ;
<21,0>	0000003C  03 23 05 00 ;        lw x6, 0(x10)
<22,0>	00000040  83 23 85 00 ;        lw x7, 8(x10)
<23,0>	00000044  03 24 0D 00 ;        lw x8, 0(s10)
#
# Debug Data
#
.debug:

#
#
# Assembling: OK