# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: RV32I
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: C:\Users\Leo\Desktop\FRISCV\FRISCV-apps\asm\src\friscv_program.a
#
#
<1,0>	00000000  37 01 00 00 ;        lui sp, %hi(0x80)            ;inicijalizacija stoga
<2,0>	00000004  13 01 01 08 ;        addi sp, sp, %lo(0x80)
<3,0>	                      ;
<4,0>	                      ;        ;postavljanje inicijalnih vrijednosti registara
<5,0>	00000008  13 05 00 70 ;        addi x10, x0, 0x700 ;pocetna adresa memorije
<6,0>	0000000C  93 05 00 67 ;        addi x11, x0, 0x670; 0b0110_0111_000
<7,0>	00000010  13 06 00 76 ;        addi x12, x0, 0x760; 0b0111_0110_000
<8,0>	00000014  93 06 00 13 ;        addi x13, x0, 0x130
<9,0>	00000018  13 07 00 14 ;        addi x14, x0, 0x140
<10,0>	0000001C  93 07 00 15 ;        addi x15, x0, 0x150
<11,0>	00000020  13 08 00 16 ;        addi x16, x0, 0x160
<12,0>	00000024  93 08 00 17 ;        addi x17, x0, 0x170
<13,0>	00000028  13 09 00 18 ;        addi x18, x0, 0x180
<14,0>	0000002C  93 09 40 00 ;        addi x19, x0, 0x4
<15,0>	                      ;
<16,0>	                      ;        ;arit operacije
<17,0>	00000030  33 0A B6 00 ;        add x20, x12, x11
<18,0>	00000034  B3 0A DA 40 ;        sub x21, x20, x13 ;hazard
<19,0>	00000038  33 8B FA 00 ;        add x22, x21, x15 ;hazard
<20,0>	0000003C  B3 8B 1A 41 ;        sub x23, x21, x17 ;hazard
<21,0>	00000040  33 0C 3B 01 ;        add x24, x22, x19 ;hazard
<22,0>	                      ;
<23,0>	00000044  23 20 45 01 ;        sw x20, 0(x10)
<24,0>	00000048  23 22 55 01 ;        sw x21, 4(x10)
<25,0>	0000004C  23 24 65 01 ;        sw x22, 8(x10)
<26,0>	00000050  23 26 75 01 ;        sw x23, 12(x10)
<27,0>	00000054  23 28 85 01 ;        sw x24, 16(x10)
<28,0>	                      ;
<29,0>	                      ;        ;log naredbe
<30,0>	00000058  33 7A B6 00 ;        and x20, x12, x11
<31,0>	0000005C  93 7A FA 0F ;        andi x21, x20, 255 ;hazard
<32,0>	00000060  33 EB FA 00 ;        or x22, x21, x15 ;hazard
<33,0>	00000064  93 6B 1B 01 ;        ori x23, x22, 17 ;hazard
<34,0>	00000068  33 CC 3B 01 ;        xor x24, x23, x19 ;hazard
<35,0>	0000006C  93 4C 1C 01 ;        xori x25, x24, 17 ;hazard
<36,0>	                      ;
<37,0>	00000070  23 2A 45 01 ;        sw x20, 20(x10)
<38,0>	00000074  23 2C 55 01 ;        sw x21, 24(x10)
<39,0>	00000078  23 2E 65 01 ;        sw x22, 28(x10)
<40,0>	0000007C  23 20 75 03 ;        sw x23, 32(x10)
<41,0>	00000080  23 22 85 03 ;        sw x24, 36(x10)
<42,0>	00000084  23 24 95 03 ;        sw x25, 40(x10)
<43,0>	                      ;
<44,0>	                      ;        ;pomaci
<45,0>	00000088  33 1A 36 01 ;        sll x20, x12, x19
<46,0>	0000008C  93 1A 1A 01 ;        slli x21, x20, 17 ;hazard
<47,0>	00000090  33 DB 3A 01 ;        srl x22, x21, x19 ;hazard
<48,0>	00000094  93 5B 4B 00 ;        srli x23, x22, 4 ;hazard
<49,0>	00000098  13 9C 8B 00 ;        slli x24, x23, 8 ;hazard
<50,0>	0000009C  B3 5C 3C 41 ;        sra x25, x24, x19 ;hazard
<51,0>	000000A0  13 DD 4C 40 ;        srai x26, x25, 4 ;hazard
<52,0>	                      ;
<53,0>	000000A4  23 26 45 03 ;        sw x20, 44(x10)
<54,0>	000000A8  23 28 55 03 ;        sw x21, 48(x10)
<55,0>	000000AC  23 2A 65 03 ;        sw x22, 52(x10)
<56,0>	000000B0  23 2C 75 03 ;        sw x23, 56(x10)
<57,0>	000000B4  23 2E 85 03 ;        sw x24, 60(x10)
<58,0>	000000B8  23 20 95 05 ;        sw x25, 64(x10)
<59,0>	000000BC  23 2C A5 09 ;        sw x26, 152(x10)
<60,0>	                      ;
<61,0>	                      ;        ;posebni slucajevi aritmetickih operacija
<62,0>	000000C0  33 0D 7B 01 ;        add x26, x22, x23 ;pozitivni + negativni
<63,0>	000000C4  B3 0D 9C 01 ;        add x27, x24, x25 ; negativni plus negativni
<64,0>	000000C8  33 0E 7B 41 ;        sub x28, x22, x23 ; pozitivni minus negativni
<65,0>	000000CC  B3 0E 9C 41 ;        sub x29, x24, x25 ; negativni minus negativni
<66,0>	000000D0  33 8F 6B 41 ;        sub x30, x23, x22 ; negativni minus pozitivni
<67,0>	                      ;
<68,0>	000000D4  23 22 A5 05 ;        sw x26, 68(x10)
<69,0>	000000D8  23 24 B5 05 ;        sw x27, 72(x10)
<70,0>	000000DC  23 26 C5 05 ;        sw x28, 76(x10)
<71,0>	000000E0  23 28 D5 05 ;        sw x29, 80(x10)
<72,0>	000000E4  23 2A E5 05 ;        sw x30, 84(x10)
<73,0>	                      ;
<74,0>	                      ;        ;usporedbe
<75,0>	000000E8  33 2A B6 00 ;        slt x20, x12, x11
<76,0>	000000EC  93 AA D6 00 ;        slti x21, x13, 13
<77,0>	000000F0  33 BB F6 00 ;        sltu x22, x13, x15
<78,0>	000000F4  93 BB 16 01 ;        sltiu x23, x13, 17
<79,0>	000000F8  33 AC C5 00 ;        slt x24, x11, x12
<80,0>	000000FC  93 AC 06 20 ;        slti x25, x13, 512
<81,0>	00000100  33 BD D7 00 ;        sltu x26, x15, x13
<82,0>	00000104  93 BD 06 20 ;        sltiu x27, x13, 512
<83,0>	                      ;
<84,0>	                      ;        
<85,0>	00000108  23 2C 45 05 ;        sw x20, 88(x10)
<86,0>	0000010C  23 2E 55 05 ;        sw x21, 92(x10)
<87,0>	00000110  23 20 65 07 ;        sw x22, 96(x10)
<88,0>	00000114  23 22 75 07 ;        sw x23, 100(x10)
<89,0>	00000118  23 24 85 07 ;        sw x24, 104(x10)
<90,0>	0000011C  23 26 95 07 ;        sw x25, 108(x10)
<91,0>	00000120  23 28 A5 07 ;        sw x26, 112(x10)
<92,0>	00000124  23 2A B5 07 ;        sw x27, 116(x10)
<93,0>	                      ;
<94,0>	00000128  63 1A 05 0C ;        bne x10, x0, poslije
<95,0>	                      ;
<96,0>	                      ;program 
<97,0>	0000012C  13 0F F0 0F ;        addi x30, x0, 0xFF; - dobro
<98,0>	00000130  93 0F 10 01 ;        addi x31, x0, 0x11; - lose
<99,0>	                      ;        ;postavljanje registara da zadovoljimo/ne zadovoljimo uvjete skokova
<100,0>	00000134  93 05 10 00 ;        addi x11, x0, 0x1
<101,0>	00000138  13 06 20 00 ;        addi x12, x0, 0x2
<102,0>	                      ;        ;razni skokovi, 1, 2 -> 11,12 -> 3,4 -> 9,10 -> 7,8 -> 5,6 -> kraj
<103,0>	                      ;
<104,0>	0000013C  63 8C C5 08 ;prvi    beq x11, x12, jedest  ;nije istinit jednako
<105,0>	00000140  23 2C E5 07 ;        sw x30, 120(x10)
<106,0>	00000144  93 05 30 03 ;        addi x11, x0, 0x33
<107,0>	00000148  13 06 30 03 ;        addi x12, x0, 0x33
<108,0>	0000014C  63 84 C5 08 ;drugi   beq x11, x12,     jedest  ;istinit
<109,0>	00000150  23 2C F5 07 ;        sw x31, 120(x10)
<110,0>	00000154  93 05 20 00 ;treci   addi x11, x0, 0x2
<111,0>	00000158  13 06 20 00 ;        addi x12, x0, 0x2
<112,0>	0000015C  63 9C C5 04 ;        bne x11, x12,     devet   ;nije istinit nije jednako
<113,0>	00000160  23 20 E5 09 ;        sw x30, 128(x10)
<114,0>	00000164  93 05 10 00 ;        addi x11, x0, 0x1
<115,0>	00000168  13 06 20 00 ;        addi x12, x0, 0x2
<116,0>	0000016C  63 94 C5 04 ;cet     bne x11, x12,     devet   ;istinit 
<117,0>	00000170  23 20 F5 09 ;        sw x31, 128(x10)
<118,0>	00000174  93 05 30 00 ;peti    addi x11, x0, 0x3
<119,0>	00000178  13 06 20 00 ;        addi x12, x0, 0x2
<120,0>	0000017C  63 CC C5 06 ;        blt x11, x12,     kraj    ;nije istinit manje
<121,0>	00000180  23 26 E5 09 ;        sw x30, 140(x10)
<122,0>	00000184  93 05 10 00 ;        addi x11, x0, 0x1
<123,0>	00000188  13 06 20 00 ;        addi x12, x0, 0x2
<124,0>	0000018C  63 C4 C5 06 ;sesti   blt x11, x12,     kraj    ;istinit
<125,0>	00000190  23 26 F5 09 ;        sw x31, 140(x10)
<126,0>	00000194  93 05 10 00 ;sedam   addi x11, x0, 0x1
<127,0>	00000198  13 06 20 00 ;        addi x12, x0, 0x2
<128,0>	0000019C  E3 DC C5 FC ;        bge x11, x12,    peti    ;nije istinit veće
<129,0>	000001A0  23 24 E5 09 ;        sw x30, 136(x10)
<130,0>	000001A4  93 05 30 00 ;        addi x11, x0, 0x3
<131,0>	000001A8  13 06 20 00 ;        addi x12, x0, 0x2
<132,0>	000001AC  E3 D4 C5 FC ;osam    bge x11, x12,     peti    ;istinit
<133,0>	000001B0  23 24 F5 09 ;        sw x31, 136(x10)
<134,0>	000001B4  93 05 30 00 ;devet   addi x11, x0, 0x3
<135,0>	000001B8  13 06 20 00 ;        addi x12, x0, 0x2
<136,0>	000001BC  E3 EC C5 FC ;        bltu x11, x12,    sedam   ;nije istinit manje unsigned
<137,0>	000001C0  23 22 E5 09 ;        sw x30, 132(x10)
<138,0>	000001C4  93 05 10 00 ;        addi x11, x0, 0x1
<139,0>	000001C8  13 06 20 00 ;        addi x12, x0, 0x2
<140,0>	000001CC  E3 E4 C5 FC ;deset   bltu x11, x12,    sedam   ;istinit
<141,0>	000001D0  23 22 F5 09 ;        sw x31, 132(x10)
<142,0>	000001D4  93 05 10 00 ;jedest  addi x11, x0, 0x1
<143,0>	000001D8  13 06 20 00 ;        addi x12, x0, 0x2
<144,0>	000001DC  E3 FC C5 F6 ;        bgeu x11, x12,    treci   ;nije istinit veće unsigned
<145,0>	000001E0  23 2E E5 07 ;        sw x30, 124(x10)
<146,0>	000001E4  93 05 30 00 ;        addi x11, x0, 0x3
<147,0>	000001E8  13 06 20 00 ;        addi x12, x0, 0x2
<148,0>	000001EC  E3 F4 C5 F6 ;dvaest  bgeu x11, x12,    treci   ;istinit
<149,0>	000001F0  23 2E F5 07 ;        sw x31, 124(x10)
<150,0>	000001F4  93 0A 10 10 ;kraj    addi x21, x0, 0x101
<151,0>	000001F8  67 80 00 00 ;        jalr    x0, 0(ra)
<152,0>	                      ;
<153,0>	                      ;poslije
<154,0>	000001FC  93 0D 50 05 ;        addi x27, x0, 0x55
<155,0>	                      ;        
<156,0>	00000200  EF 00 80 00 ;        jal ra, prog2
<157,0>	                      ;
<158,0>	00000204  63 1E 10 00 ;        bne x0, x1, pos2
<159,0>	                      ;
<160,0>	                      ;prog2   
<161,0>	00000208  13 01 C1 FF ;        addi sp, sp, -4                 ; smanjivanje sp                                spremanje konteksta
<162,0>	0000020C  23 20 11 00 ;        sw ra, 0(sp)                    ; spremanje podatka na stog
<163,0>	                      ;
<164,0>	00000210  EF F0 DF F1 ;        jal ra, program
<165,0>	                      ;
<166,0>	00000214  83 20 01 00 ;        lw ra, 0(sp)                    ;obnova registra za registar x6
<167,0>	00000218  13 01 41 00 ;        addi sp, sp, 4                  ;povećaj sp za 4
<168,0>	                      ;
<169,0>	0000021C  67 80 00 00 ;        jalr    x0, 0(ra)
<170,0>	                      ;pos2
<171,0>	00000220  B7 52 34 12 ;        lui x5, %hi(0x12345678)            
<172,0>	00000224  93 82 82 67 ;        addi x5, x5, %lo(0x12345678)
<173,0>	00000228  17 02 00 00 ;        auipc x4,%pcrel_hi(test)    
<174,0>	0000022C  13 02 42 00 ;test    addi x4,x4,%pcrel_lo(test)  
<175,0>	00000230  23 28 45 08 ;        sw x4, 144(x10)
<176,0>	00000234  23 2A 55 08 ;        sw x5, 148(x10)        
<177,0>	                      ;
<178,0>	00000238  93 05 F0 0F ;        addi x11, x0, 0xff
<179,0>	0000023C  93 95 85 00 ;        slli x11, x11, 8
<180,0>	00000240  93 85 F5 0F ;        addi x11, x11, 0xff
<181,0>	00000244  93 95 85 00 ;        slli x11, x11, 8
<182,0>	00000248  93 85 F5 0F ;        addi x11, x11, 0xff
<183,0>	0000024C  93 95 85 00 ;        slli x11, x11, 8
<184,0>	00000250  93 85 F5 0F ;        addi x11, x11, 0xff
<185,0>	00000254  23 2E B5 08 ;        sw x11, 156(x10)
<186,0>	00000258  33 00 00 00 ;        add x0, x0, x0; kraj
<187,0>	0000025C  37 1D 00 00 ;        lui s10, %hi(0xFFC);
<188,0>	00000260  13 0D CD FF ;        addi s10, s10, %lo(0xFFC);
<189,0>	00000264  93 0D 70 01 ;        addi s11, x0, 0x17;
<190,0>	00000268  23 20 BD 01 ;        sw s11, 0(s10)
#
# Debug Data
#
.debug:

#
#
# Assembling: OK