# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: RV32I
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: C:\Users\Leo\Desktop\FRISCV\FRISCV-apps\asm\src\ledice.a
#
#
<1,0>	00000000  37 0D 01 00 ;        lui s10, %hi(0x10000);
<2,0>	00000004  13 0D 0D 00 ;        addi s10, s10, %lo(0x10000);
<3,0>	00000008  B7 0D 02 00 ;        lui s11, %hi(0x20000);
<4,0>	0000000C  93 8D 0D 00 ;        addi s11, s11, %lo(0x20000);
<5,0>	00000010  13 05 10 00 ;        addi x10, x0, 0b1
<6,0>	00000014  93 05 00 00 ;        addi x11, x0, 0x0
<7,0>	00000018  13 02 40 06 ;        addi x4, x0, 100
<8,0>	                      ;pocetak 
<9,0>	0000001C  B7 02 10 00 ;        lui x5, %hi(0x100000);
<10,0>	00000020  93 82 02 00 ;        addi x5, x5, %lo(0x100000);
<11,0>	00000024  93 82 F2 FF ;l1      addi x5,x5, -1
<12,0>	00000028  E3 9E 02 FE ;        bne x5, x0, l1        
<13,0>	0000002C  23 20 AD 00 ;        sw x10, 0(s10)
<14,0>	                      ;;        sw x10, 0(s11)
<15,0>	                      ;
<16,0>	00000030  B7 02 10 00 ;        lui x5, %hi(0x100000);
<17,0>	00000034  93 82 02 00 ;        addi x5, x5, %lo(0x100000);
<18,0>	00000038  93 82 F2 FF ;l2      addi x5,x5, -1
<19,0>	0000003C  E3 9E 02 FE ;        bne x5, x0, l2        
<20,0>	00000040  23 20 BD 00 ;        sw x11, 0(s10)
<21,0>	                      ;
<22,0>	00000044  03 A6 0D 00 ;        lw x12, 0(s11)
<23,0>	00000048  23 A0 CD 00 ;        sw x12, 0(s11)
<24,0>	                      ;
<25,0>	0000004C  13 02 F2 FF ;        addi x4, x4, -1
<26,0>	00000050  E3 16 02 FC ;        bne x4, x0, pocetak
<27,0>	                      ;
<28,0>	00000054  37 1D 00 00 ;        lui s10, %hi(0xFFC);
<29,0>	00000058  13 0D CD FF ;        addi s10, s10, %lo(0xFFC);
<30,0>	0000005C  93 0D 70 01 ;        addi s11, x0, 0x17;
<31,0>	00000060  23 20 BD 01 ;        sw s11, 0(s10)
#
# Debug Data
#
.debug:

#
#
# Assembling: OK