
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_CLK_GEN_DEVICE_ID,
		XPAR_AXI_GPIO_CLK_GEN_BASEADDR,
		XPAR_AXI_GPIO_CLK_GEN_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_CLK_GEN_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_DEBUG_DEVICE_ID,
		XPAR_AXI_GPIO_DEBUG_BASEADDR,
		XPAR_AXI_GPIO_DEBUG_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_DEBUG_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_DEBUG_MEM_ADDR_DEVICE_ID,
		XPAR_AXI_GPIO_DEBUG_MEM_ADDR_BASEADDR,
		XPAR_AXI_GPIO_DEBUG_MEM_ADDR_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_DEBUG_MEM_ADDR_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_DEBUG_MEM_DATA_DEVICE_ID,
		XPAR_AXI_GPIO_DEBUG_MEM_DATA_BASEADDR,
		XPAR_AXI_GPIO_DEBUG_MEM_DATA_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_DEBUG_MEM_DATA_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RST_N_EXTERN_DEVICE_ID,
		XPAR_AXI_GPIO_RST_N_EXTERN_BASEADDR,
		XPAR_AXI_GPIO_RST_N_EXTERN_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RST_N_EXTERN_IS_DUAL
	}
};


